### ISSUE TITLE
Requests not handling properly

### ISSUE THREAD

**Issue by swissbeats93** [aforward/stripe-post#1]
Hi, so i've been reading through this library to get an idea of how to develop something simiar but for Judopay.

Upon testing the Request  module via the example given, I'm getting the following error:

`StripePost.Request.create(resource: "logs").url`

> `** (FunctionClauseError) no function clause matching in Keyword.take/2    
    
    The following arguments were given to Keyword.take/2:
    
        # 1
        []
    
        # 2
        :http_opts
    
    Attempted function clauses (showing 1 out of 1):
    
        def take(keywords, keys) when is_list(keywords) and is_list(keys)
    
    (elixir 1.12.2) lib/keyword.ex:997: Keyword.take/2
    (stripe_post 0.5.1) lib/stripe_post/opts.ex:42: StripePost.Opts.merge/3
    (stripe_post 0.5.1) lib/stripe_post/request.ex:64: StripePost.Request.create/1
`

**Comment by swissbeats93** [comment]
> Hi, so i've been reading through this library to get an idea of how to develop something simiar but for Judopay.
> 
> Upon testing the Request module via the example given, I'm getting the following error:
> 
> `StripePost.Request.create(resource: "logs").url`
> 
> > `** (FunctionClauseError) no function clause matching in Keyword.take/2
> 
> ```
> The following arguments were given to Keyword.take/2:
> 
>     # 1
>     []
> 
>     # 2
>     :http_opts
> 
> Attempted function clauses (showing 1 out of 1):
> 
>     def take(keywords, keys) when is_list(keywords) and is_list(keys)
> 
> (elixir 1.12.2) lib/keyword.ex:997: Keyword.take/2
> (stripe_post 0.5.1) lib/stripe_post/opts.ex:42: StripePost.Opts.merge/3
> (stripe_post 0.5.1) lib/stripe_post/request.ex:64: StripePost.Request.create/1
> ```
> 
> `

PS: So i fixed the error by wrapping the :http_opts with brackets to [:http_opts] in the Request module
